languageCode = "en"
languageName = "English"
weight = 1
title = "Neil's Blog"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/img/blog_logo.png"
  description = "A blog where I share insights from my journey through coding projects, tackle real-world development challenges, and break down key software engineering concepts. Whether you're a fellow developer or just curious about tech, this site details lessons I've learned from hands-on experience."
  copyright = "© 2025 Neil Agrawal"

[params.author]
  name = "Neil Agrawal"
  email = "neil@neilagrawal.com"
  image = "img/blog_logo.png"
  headline = "Software Developer & Computer Science Student"
  bio = "I'm a computer science student passionate about artificial intelligence, software engineering, and solving complex problems through code."
  links = [
    { github = "https://github.com/NeagDolph" },
  ]