[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  HUGO_VERSION = "0.140.2"

[build]
  command = "yarn build:webpack && hugo -d dist"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:webpack && hugo -d dist -D -F"

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true